### ISSUE TITLE
knife tidy backup clean throws an error with chef-dk/ws that includes chef >= 15.0.293

### ISSUE THREAD

**Issue by teknofire** [chef/knife-tidy#109]
# Version:

Knife-Tidy version: 2.0.1
Chef Workstation version: 0.9.42
Chef Infra Client version: 15.3.14

# Environment:

Test in Linux and OSX with Chef-Server 13

# Scenario:

`knife tidy backup clean` no longer works on backups with an organization that has more than one version of the same cookbook. Removing all but the latest versions of the cookbooks from the backup allows it to finish without an error.

I suspect that the changes in https://github.com/chef/chef/pull/7794 are the cause of this.  It removes support for multiple cookbooks with the same `cookbook name` in the same `cookbook_path`, which is what happens when `knife ec backup` downloads a copy of each cookbook version.

The call to the code that triggers the error is https://github.com/chef/knife-tidy/blob/master/lib/chef/knife/tidy_backup_clean.rb#L167 

Stacktrace of the error:
```
Traceback (most recent call last):
	19: from /Users/wfisher/.gem/ruby/2.6.3/bin/knife:23:in `<main>'
	18: from /Users/wfisher/.gem/ruby/2.6.3/bin/knife:23:in `load'
	17: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/bin/knife:24:in `<top (required)>'
	16: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/application/knife.rb:162:in `run'
	15: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/knife.rb:222:in `run'
	14: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
	13: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	12: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
	11: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:53:in `run'
	10: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:53:in `each'
	 9: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:65:in `block in run'
	 8: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:165:in `load_cookbooks'
	 7: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:315:in `for_each_cookbook_basename'
	 6: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:315:in `each'
	 5: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:319:in `block in for_each_cookbook_basename'
	 4: from /Users/wfisher/.gem/ruby/2.6.3/gems/knife-tidy-2.0.3/lib/chef/knife/tidy_backup_clean.rb:167:in `block in load_cookbooks'
	 3: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/cookbook_loader.rb:87:in `load_cookbook'
	 2: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/cookbook_loader.rb:173:in `cookbook_version_loaders'
	 1: from /Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/cookbook_loader.rb:173:in `each'
/Users/wfisher/.gem/ruby/2.6.3/gems/chef-15.3.14/lib/chef/cookbook_loader.rb:177:in `block in cookbook_version_loaders': Cookbook merging is no longer supported, the cookbook named test can only appear once in the cookbook_path (Chef::Exceptions::CookbookMergingError)
```

# Steps to Reproduce:

1. Follow the instructions from https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy/ to create a backup using `knife ec backup backup_directory -c /etc/opscode/pivotal.rb`
2. Run `knife tidy backup clean --backup-path backup_directory` 
3. Command throws an error 

# Expected Result:

`knife tidy backup clean` should complete successfully

# Actual Result:

An error is thrown: `ERROR: Chef::Exceptions::CookbookMergingError: Cookbook merging is no longer supported, the cookbook named test can only appear once in the cookbook_path`

**Comment by sean-horn** [comment]
Yes, reproduced today through the same mechanism, different command

Example: I create a copy of `cookbooks` to work with and change my config to point at both copies. Then, if I remove one or the other of those directories, or remove one or the other entry from the .chef/config.rb cookbook_path array, the cookbook upload works fine.

```
chef-repo# knife --version
Chef Infra Client: 15.4.45

chef-repo# # grep cookbook_path .chef/config.rb
cookbook_path [ "#{Dir.pwd}/cookbooks", "#{Dir.pwd}/cookbooks-copy" ]

chef-repo# cp -pr cookbooks cookbooks-copy

chef-repo# ls -ald cookbooks*
drwxr-xr-x 13 root root 4096 Dec 14  2018 cookbooks
drwxr-xr-x 13 root root 4096 Dec 14  2018 cookbooks-copy

chef-repo ()# knife cookbook upload mynewcookbook
ERROR: Chef::Exceptions::CookbookMergingError: Cookbook merging is no longer supported, the cookbook named mynewcookbook can only appear once in the cookbook_path
```
